FROM continuumio/miniconda3:22.11.1

RUN apt-get update
COPY environment.yml .
RUN conda env create -f environment.yml
RUN pip install SimpleITK
RUN pip install scikit-image
RUN pip install git+https://github.com/gatocor/registration-tools