FROM continuumio/miniconda3:4.12.0

RUN apt-get update
COPY environment.yaml .
RUN conda install cmake make
RUN apt-get install g++ gcc -y
RUN conda env create -f environment.yml
RUN pip install git+https://github.com/GuignardLab/registration-tools
